spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/tobehomeserver
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database-host}:3306/tobehome?createDatabaseIfNotExist=true
    username: tobehome
    password: ${database-password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true //sout 통해 출력
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace